# Generated by Django 4.2.7 on 2023-12-06 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestmodel',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('5b7e72d6-558a-492f-8651-d9e2e794c32f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
