# Generated by Django 4.2.7 on 2023-12-06 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_contestmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestmodel',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('6c2fa7a1-9a4c-4fbb-b703-0a04b03afce0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
