# Generated by Django 4.2.7 on 2023-12-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
