# Generated by Django 4.2.7 on 2023-12-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0002_contestmodel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
