# Generated by Django 4.2.7 on 2023-12-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0002_questionmodel_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='submitted',
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
