# Generated by Django 4.2.7 on 2023-12-10 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0004_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='code',
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='question',
        ),
        migrations.CreateModel(
            name='responseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.JSONField()),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Contest.questionmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='submissions',
            name='response',
            field=models.ManyToManyField(to='Contest.responsemodel'),
        ),
    ]
