# Generated by Django 4.2.7 on 2023-12-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0005_remove_submissions_code_remove_submissions_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsemodel',
            old_name='question',
            new_name='question_id',
        ),
    ]
